### PR TITLE
Replace example.org with oapass.org in latest context

### PR DESCRIPTION
**Pull request by karenhanson**
Eliminates the use of `example.org/pass` namespace, uses official `oapass.org` url as namespace instead.
Since this will break existing code, changes context version to 2.2.

### CODE REVIEW

**Comment by birkland** [comment]
Would it be possible to use `http://oapass.org/ns/pass#`  instead? (the important part being ending in a hash)?  The reason:  If we ever publish an ontology (which we ought to if this expands beyond JHU), there will be an expectation that the URIs for terms actually resolve to something.  Using a hash means that all we need to do is publish a single document in order to do so.  Using `/` means a more complicated mechanism of resolution.

**Comment by karenhanson** [comment]
@birkland sure!

**Comment by karenhanson** [comment]
@birkland realising this will actually break things unless everything is updated at once. I think this should be a new version and I will increment to 3.0. Sound right?

**Comment by birkland** [comment]
Yes, I think so.  It'll be a breaking change for clients that deals with
the model as rdf (maybe deposit, sort of?), it will be much less impactful
for anything that deals with the model as compact json (ember, Java
client).

**Pull request merged**
