### PR TITLE
Update context based on documentation

### PR DESCRIPTION
**Pull request by birkland**
Added and tweaked attributes based on documentation.  Did not remove
attributes that are not mentioned in the docs.

### CODE REVIEW

**Comment by markpatton** [comment]
This looks fine. The issue is that pass-ember won't be able to use it without code changes. There needs to be a context which can be used by pass-docker. Also note that pass-docker cannot use the current context until @type: @id is added to the submissions term.

**Comment by birkland** [comment]
@markpatton Yes.  This is the definitive context, so the ember app would need to be updated.

**Comment by markpatton** [comment]
@birkland That's a blocker for me then until the ember app has been updated. Looking at the changes, it may be quite a bit of work. I think we need to have a context hosted elsewhere which pass-docker can use.

**Comment by birkland** [comment]
@markpatton All applications reading/writing from the same repository ought to have a common sense of the model, and use the same context.  So if this is merged, then the ember app needs to be updated.  Two contexts does not sound viable, unless it's for local testing prior to suggesting changes to the shared context

**Comment by karenhanson** [comment]
when we are ready to merge this, we will need to bring it in line with the last few PRs that change the model slightly. I thought about starting to do PRs to your branch, but I think it might be easier to tackle them all at once.

**Pull request merged**
