### PR TITLE
Associates a URI with each DepositStatus 

### PR DESCRIPTION
**Pull request by emetsger**
This change proposes that each status for `Deposit` be assigned a URI, and updates the documentation for the `DepositStatus` to be congruent with its usage by Deposit Services.  Includes updated verbiage describing _intermediate_ and _terminal_ statuses.

The URIs being proposed are:

*  http://oapass.org/ns/status/deposit#submitted
*  http://oapass.org/ns/status/deposit#accepted
*  http://oapass.org/ns/status/deposit#rejected
*  http://oapass.org/ns/status/deposit#failed

### CODE REVIEW

**Comment by emetsger** [comment]
This PR doesn't modify the model at all.  Right now the only place that I'm aware of that desires URIs for Deposit statuses are Deposit Services.  Arguably, this PR doesn't have to be accepted but to me it makes sense for URIs to be used as status values.

There is a PR for the PASS client which provides support for parsing status URIs as `DepositStatus` objects.

**Comment by karenhanson** [comment]
Deposit status is displayed on the Submission details page, so this would require an ember update as well unfortunately. I think this is a good idea though and we should do this for all statuses.

**Comment by emetsger** [comment]
Actually @karenhanson no updates should be required.  This PR makes no changes to existing statuses.  It allows URIs to be used instead, but doesn't require them.  The old status strings still work.

**Comment by karenhanson** [comment]
@emetsger oh ok, I just looked at the java client PR - I get it now.

**Pull request merged**
